<a href="https://colab.research.google.com/github/krypton20/LinearAlgebra_2ndSem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Laboratory 4 : Matrices

In the previous laboratory activity, the students have learned and applied the basic concepts, principles, and techniques of Python fundamentals. However, this laboratory activity focuses on the application of matrices in Python in relation to the linear system of equations. Through this activity, the students will be able to learn the application of matrices in programming together with its basic operations and techniques. Upon learning its applications, the students will be able to apply their knowledge in translating matrix equations and operations using Python.


#Discussion 


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

- Numerical Python or "numpy" in short, supports a broad range of mathematical operations on arrays. It extends Python with sophisticated data formats that ensure fast array and matrix computations, as well as a vast library of elevated numerical methods that work on these matrices and arrays.
- Matplotlib.pyplot is a set of algorithms that enable matplotlib to operate similarly to MATLAB. Each pyplot function modifies a figure in certain way
- Scipy.linalg contains a variety of tools for solving linear algebra applications, such as functions for conducting matrix operations.

##Matrices

A matrix is a two-dimensional rectangle array that holds data in rows and columns. The matrix may hold any form of data, including numbers, strings, equations, and so on. The data is organized horizontally as rows and vertically as columns. Matrix data structures, on the other hand, are vital for various mathematical and scientific operations.

Matrix notation and utilization is likely one of the three cornerstones of modern calculations.  Matrices are also useful for representing complicated equations or several interconnected equations, ranging from two dimensional equations to desired number of equations.

For instance, let I, O and E as system of equations.

$$
I = \left\{
    \begin{array}\
        4a + 20b \\ 
        7a - 9b
    \end{array}
\right. \\
O = \left\{
    \begin{array}\
        2a+7b+3c \\ 
        3a -2b -c \\
        -100a + 4b +2c
    \end{array}
\right. \\
E = \left\{
    \begin{array}\
        30a+20b+7c-d \\ 
        4a -3b -2c+ 10d \\
        -100a + 4b +2c+3d
    \end{array}
\right.
$$

\\

In this representation, we could observe that I is a system of  equations with 2 parameters. While O and E is a system of 3 equations with 3 and 4 parameters respectively. However, their representation in matrices are as follows:


:$$
I=\begin{bmatrix} 4 & 20 \\ 7 & {9} \end{bmatrix} \\
O=\begin{bmatrix} 2 & 7 & 3 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
E=\begin{bmatrix} 30 & 20 & 7 & -1\\ 4 & -3 & -2 & 10\\ 100 & 4 & 2 & 3\end{bmatrix}
$$




##Declaring Matrices

In this laboratory activity, system of linear equations will be represented as matrices.The things or numbers included in matrices are referred to as the matrix's elements. Matrixes have a collection of list-like structure because these items are grouped and sorted in rows and columns. This generalization may be expressed in the same way in the following equation:

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
#Declaring Matrices
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')
                                                    

In [ ]:
## 2 x 2 Matrix
M = np.array([
    [20, 100],
    [47, 21]
])
describe_mat(M)


Matrix:
[[ 20 100]
 [ 47  21]]

Shape:	(2, 2)
Rank:	2



In [ ]:
#3 x 3 Matrix
R = np.array([
    [9,12,3],
    [11,2,4],
    [4,3,8]
])
describe_mat(R)


Matrix:
[[ 9 12  3]
 [11  2  4]
 [ 4  3  8]]

Shape:	(3, 3)
Rank:	2



In [ ]:
#4 x 5 Matrix
R = np.array([
    [1,16,3,0,14],
    [10,21,14,0,9],
    [4,3,8,6,2],
    [20,9,2,1,3]
])
describe_mat(R)


Matrix:
[[ 1 16  3  0 14]
 [10 21 14  0  9]
 [ 4  3  8  6  2]
 [20  9  2  1  3]]

Shape:	(4, 5)
Rank:	2



In [ ]:
P = np.array([[[20,19,18,17,16]]])
describe_mat(P)

Matrix:
[[[20 19 18 17 16]]]

Shape:	(1, 1, 5)
Rank:	3



#Categoring Matrices

Matrices have different types, and they can be classified according to shape and element values.


##Row and Column Matrices

These are matrices that are also known as "Row and Column Vectors." Row Matrices is described by a single row that has a shape of 1 x n, while Column Matrices is defined as a single column with a shape of n x 1. A row is displayed vertically, and a column is shown horizontally. [1]


In [ ]:
## Declaring a Row Matrix

row_matrix_1D = np.array([
        30, 17, 3               
]) 
row_matrix_2D = np.array([
      [7,2,9, -14]                 
]) 
describe_mat(row_matrix_1D)
describe_mat(row_matrix_2D)

Matrix:
[30 17  3]

Shape:	(3,)
Rank:	1

Matrix:
[[  7   2   9 -14]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

column_matrix = np.array([
        [20],
        [15],
        [1],
        [14]
]) 
describe_mat(column_matrix)

Matrix:
[[20]
 [15]
 [ 1]
 [14]]

Shape:	(4, 1)
Rank:	2



##Square Matrices

The matrices in Square Matrices are arranged in such a way that the sizes of both row and column are equal. In the code cell below, we can distinguish if the matrix is a square matrix or not through the descriptor function, which will print out True or False after the "Is Square:" [2]

In [ ]:
def describe_mat(matrix):
    test_for_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\ntest_for_square: {test_for_square}\n')

In [ ]:
matrix_1 = np.array([
             [12,2,3],
             [3,3,3], 
             [8,1,2]            
]) 
matrix_2 = np.array([
             [9,2,1],
             [8,3,7]           

])
describe_mat(matrix_1)
describe_mat(matrix_2)

Matrix:
[[12  2  3]
 [ 3  3  3]
 [ 8  1  2]]

Shape:	(3, 3)
Rank:	2
test_for_square: True

Matrix:
[[9 2 1]
 [8 3 7]]

Shape:	(2, 3)
Rank:	2
test_for_square: False



#According to element 

##Null Matrix


The term "null" simple means "empty". In a Null matrix, it is a type of matrix according to element that has an empty matrix or does not contain any element. [3]


In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
           test_for_square = True if matrix.shape[0] == matrix.shape[1] else False
           print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\ntest_for_square: {test_for_square}\n')
    else:
        print('The Matrix is Null')


In [ ]:
matrix_null = np.array([])
describe_mat(matrix_null)

The Matrix is Null


##Zero Matrix

With Zero Matrix, it is easily understood that the elements to be inputted should be zero (0) only regardless of whether the matrix is a square, rectangle, or a row. [3]


In [ ]:
zero_row_matrix = np.zeros((1,8))
zero_square_matrix = np.zeros((4,4))
zero_rect_matrix = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_row_matrix}')
print(f'Zero Square Matrix: \n{zero_square_matrix}')
print(f'Zero Rectangular Matrix: \n{zero_rect_matrix}')


Zero Row Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix

As with the zero matrix, a ones matrix may be any rectangular matrix with all of its entries being ones (1s) rather than zeros (0s). In simpl terms, a matrix of ones is a matrix in which each component is equal to one.[4] 

In [ ]:
ones_row_matrix = np.ones((1,10))
ones_square_matrix = np.ones((4,4))
ones_rect_matrix = np.ones((4,3))

print(f'Ones Row Matrix: \n{ones_row_matrix}')
print(f'Ones Square Matrix: \n{ones_square_matrix}')
print(f'Ones Rectangular Matrix: \n{ones_rect_matrix}')

Ones Row Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##Diagonal Matrix

From the word itself, it is a type of matrix wherein the elements that are not in the diagonal of the matrix will be automatically zero, and the elements that are non-zero will be placed diagonally in a square matrix. [2]


In [ ]:
np.array([
    [12,0,0],
    [0,4,0],
    [0,0,1]
])

array([[12,  0,  0],
       [ 0,  4,  0],
       [ 0,  0,  1]])

In [ ]:
d = np.diag([12,7,9,3])
d


array([[12,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0,  3]])

##Identity Matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix

It is a matrix in which the values under the diagonal of the matrix will be equivalent to zero, while the values declared will only appear above the diagonal. [2]

In [ ]:
np.array([
     [1,2,3,4],
     [0,3,1,-1],
     [0,0,4,-1],
     [0,0,0,4],
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  4,  4, -1],
       [ 0,  3,  1, -1]])

##Lower Triangular Matrix

This type of matrix is the opposite of the Upper Triangular Matrix. Wherein there are no values or the elements to appear is zero above the diagonal of the matrix. The values declared are under the diagonal. [2]


In [ ]:
np.array([
     [0,0,0,4],
     [0,0,1,-1],
     [7,8,4,-1],
     [1,2,3,4],
])

array([[ 0,  0,  0,  4],
       [ 0,  0,  1, -1],
       [ 7,  8,  4, -1],
       [ 1,  2,  3,  4]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$                          
Matrix $$
\theta = \begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$



2.Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown.

G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])



$$
G = \left\{\begin{array}
5x + 7y + 8z\\
2x + 2y + 2z\\
4x + 6y + 7z
\end{array}\right.
$$


$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix} \\
$$


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

H = np.tril(G)
H




$$
H = \left\{\begin{array}
4x\\
3x + 1y\\
4x + 6y + 7z
\end{array}\right.
$$


$$
H=\begin{bmatrix} 2 & 0 & 0 \\ 3 & 3 & 0 \\ 4 & 7 & 8\end{bmatrix} \\
$$


# Matrix Algebra

##Addition

In [ ]:
A = np.array([
    [12,2,3],
    [3,3,3], 
                        
]) 
B = np.array([
    [9,2,1],
    [8,3,7]           

])
A+B

array([[21,  4,  4],
       [11,  6, 10]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[14,  4,  5],
       [ 5,  5,  5]])

## Subtraction

In [ ]:
A = np.array([
    [12,2,11],
    [3,7,3], 
                        
]) 
B = np.array([
    [9,2,1],
    [11,3,7]           

])
A-B

array([[ 3,  0, 10],
       [-8,  4, -4]])

In [ ]:
3-B

##Element-wise Multiplication


In [ ]:
A*B
np.multiply(A,B)

array([[108,   4,   3],
       [ 24,   9,  21]])

In [ ]:
2*A

array([[24,  4,  6],
       [ 6,  6,  6]])

In [ ]:
np.add(A,B)

array([[21,  4,  4],
       [11,  6, 10]])

#Activity

##Task #1

In [ ]:
#(Create a function named mat_desc() that througouhly describes a matrix, it should:
#Displays the shape, size, and rank of the matrix.
#Displays whether the matrix is square or non-square.
#Displays whether the matrix is an empty matrix.)
#Displays if the matrix is an identity, ones, or zeros matrix

def mat_desc(matrix):
    matrix = np.array(matrix)
    square = False
    print(matrix)
    print("-----------------------------------------------------")
    print("According to Shape,Size & Rank:")
    print(f'Shape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\n')
    print("-----------------------------------------------------")
    print("Matrix Classifications:")
    print("This sample matrix is a ____")
    if(matrix.shape[0] == matrix.shape[1]):
        square = True
        print("- Square Matrix")
    else:
        print("- Non-Square Matrix")
    if matrix.size == 0:
        print("- Null/Empty Matrix")
    else:
        print("-  Not an Empty Matrix")
    identity = np.identity(matrix.shape[0])
    if(square and (identity == matrix).all()):
        print("- Identity Matrix")
    else:
        print("- Not an Identity Matrix")
    one = np.ones((matrix.shape[0], matrix.shape[1]))
    if((one == matrix).all()):
        print("- Ones Matrix")
    else:
        print("- Not a Ones Matrix")
    zero = np.zeros((matrix.shape[0], matrix.shape[1]))
    if((zero == matrix).all()):
        print("- Zero Matrix")
    else:
        print("- Non-Zero Matrix")

In [ ]:
print("#Sample Matrix 1")
M = np.array([
    [4,18,12,16],
    [7,14,21,28],
    [8,16,24,32],
    [9,18,27,36]
])
mat_desc(M)


#Sample Matrix 1
[[ 4 18 12 16]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
-  Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


In [ ]:
print("#Sample Matrix 2")
P = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],   
])
mat_desc(P)

#Sample Matrix 2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(3, 4)
Size:	12
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Non-Square Matrix
-  Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Zero Matrix


In [ ]:
print("#Sample Matrix 3")
G = np.zeros((4,4))
mat_desc(G)


#Sample Matrix 2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Zero Matrix


In [ ]:
print("#Sample Matrix 4")
J = np.eye(4)

mat_desc(J)

#Sample Matrix 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
-  Not an Empty Matrix
- Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


In [ ]:
print("#Sample Matrix 4")
A = np.array([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
mat_desc(A)

#Sample Matrix 3
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Ones Matrix
- Non-Zero Matrix


In [ ]:
print("#Sample Matrix 5")
Z = np.array([
    [1,1,1,1],
    [1,22,11,23],
    [4,8,12,16],
    [3,3,6,8],
    [21,4,9,8],

])
mat_desc(Z)

#Sample Matrix 5
[[ 1  1  1  1]
 [ 1 22 11 23]
 [ 4  8 12 16]
 [ 3  3  6  8]
 [21  4  9  8]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(5, 4)
Size:	20
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Non-Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


##Task #2

In [ ]:
##Create a function named mat_operations() that takes in two matrices a input parameters it should:
#Determines if the matrices are viable for operation and returns your own error message 
#if they are not viable.
#Returns the sum of the matrices.
#Returns the difference of the matrices.
#Returns the element-wise multiplication of the matrices.
#Returns the element-wise division of the matrices.

def mat_operations(matrix_A, matrix_B):
    matrix_A = np.array(matrix_A)
    matrix_B = np.array(matrix_B)
    print('Matrix A:', matrix_A)
    print('Matrix B:', matrix_B)
    if(matrix_A.shape != matrix_B.shape):
        print('Matrix Error: The operation is not viable.')
        return
    print('By Addition: Sum of Matrices:')
    matrix_sum = matrix_A + matrix_B
    print(matrix_sum)
    print('By Subtration: Difference Matrices:')
    matrix_diff = matrix_A - matrix_B
    print(matrix_diff)
    print('By Element-wise Multiplication of Matrices:')
    matrix_multiply = np.multiply(matrix_A, matrix_B)
    print(matrix_multiply)
    print('By Element-wise Division of of Matrices:')
    matrix_divide = np.divide(matrix_A, matrix_B)
    print(matrix_divide)


In [ ]:
print("#Sample Matrix 1")
matrix_A = np.array([
    [10,2,3],
    [3,4,3], 
                        
]) 
matrix_B= np.array([
    [1,2,1],
    [8,3,7]           

])
mat_operations(matrix_A, matrix_B)

#Sample Matrix 1
Matrix A: [[10  2  3]
 [ 3  4  3]]
Matrix B: [[1 2 1]
 [8 3 7]]
By Addition: Sum of Matrices:
[[11  4  4]
 [11  7 10]]
By Subtration: Difference Matrices:
[[ 9  0  2]
 [-5  1 -4]]
By Element-wise Multiplication of Matrices:
[[10  4  3]
 [24 12 21]]
By Element-wise Division of of Matrices:
[[10.          1.          3.        ]
 [ 0.375       1.33333333  0.42857143]]


In [ ]:
print("#Sample Matrix 2")
matrix_A = np.array([
    [4,2,3,7],
    [3,4,3,1], 
    [11,4,9,2]
                        
]) 
matrix_B= np.array([
    [1,2,1],
    [8,3,7]           

])
mat_operations(matrix_A, matrix_B)

#Sample Matrix 2
Matrix A: [[ 4  2  3  7]
 [ 3  4  3  1]
 [11  4  9  2]]
Matrix B: [[1 2 1]
 [8 3 7]]
Matrix Error: The operation is not viable.


In [ ]:
print("#Sample Matrix 3")
mat_operations([[4, 2, 3], [4,1,9], [7,3,5]], [[6,2,1],[4,4,6]])
print("-----------------------------------------------------")
print("#Sample Matrix 4")
mat_operations([[3,2,1,9,1.5], [1.01,2,3,1.2,1], [8,1,8,9,2]], [[5,4,1,3,8],[8,3,4,4.1,2],[2,1,2,3,3]])
print("-----------------------------------------------------")
print("#Sample Matrix 5")
mat_operations([[1, 2, 4,2], [8,16,23,1], [4,3,1,7]], [[2,2,2,2]])

#Sample Matrix 3
Matrix A: [[4 2 3]
 [4 1 9]
 [7 3 5]]
Matrix B: [[6 2 1]
 [4 4 6]]
Matrix Error: The operation is not viable.
-----------------------------------------------------
#Sample Matrix 4
Matrix A: [[3.   2.   1.   9.   1.5 ]
 [1.01 2.   3.   1.2  1.  ]
 [8.   1.   8.   9.   2.  ]]
Matrix B: [[5.  4.  1.  3.  8. ]
 [8.  3.  4.  4.1 2. ]
 [2.  1.  2.  3.  3. ]]
By Addition: Sum of Matrices:
[[ 8.    6.    2.   12.    9.5 ]
 [ 9.01  5.    7.    5.3   3.  ]
 [10.    2.   10.   12.    5.  ]]
By Subtration: Difference Matrices:
[[-2.   -2.    0.    6.   -6.5 ]
 [-6.99 -1.   -1.   -2.9  -1.  ]
 [ 6.    0.    6.    6.   -1.  ]]
By Element-wise Multiplication of Matrices:
[[15.    8.    1.   27.   12.  ]
 [ 8.08  6.   12.    4.92  2.  ]
 [16.    1.   16.   27.    6.  ]]
By Element-wise Division of of Matrices:
[[0.6        0.5        1.         3.         0.1875    ]
 [0.12625    0.66666667 0.75       0.29268293 0.5       ]
 [4.         1.         4.         3.         0.66666667]]
-